version: '3.7'

services:
  gobworkflow:
    build:
      context: src
      target: development
    image: gob_workflow
    container_name: gobworkflow
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001
      DATABASE_PORT_OVERRIDE: 5432
      DATABASE_HOST_OVERRIDE: management_database
      GOB_SHARED_DIR: /app/shared
      GOBOPTIONS: ${GOBOPTIONS}
    volumes:
      - gob-volume:/app/shared
      - ./src/gobworkflow:/app/gobworkflow
      - ./src/tests:/app/tests
      - ./src/alembic:/app/alembic
      - ${GOB_CORE_DIR-../GOB-Core}:/app/GOB-Core

volumes:
  gob-volume:
    external: true

networks:
  default:
    name: gob-network
    external: true
