version: '3'

services:
  workflow_service:
    build: src
    container_name: workflow_service
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      DATABASE_PORT_OVERRIDE: 5432
      DATABASE_HOST_OVERRIDE: management_database
      GOB_SHARED_DIR: /app/shared
    volumes:
      - gob-volume:/app/shared

volumes:
  gob-volume:
    external: true

networks:
  default:
    external:
      name: gob-network
