"""Add process id to jobs

Revision ID: 1b9a5052cc07
Revises: 7e5fc5c3bc99
Create Date: 2020-07-29 11:51:38.294602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9a5052cc07'
down_revision = '7e5fc5c3bc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('process_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_process_id'), 'jobs', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_process_id'), table_name='jobs')
    op.drop_column('jobs', 'process_id')
    # ### end Alembic commands ###
