"""Add request uuid column to auditlog

Revision ID: 22e154a69341
Revises: 6bdbd9ff70e7
Create Date: 2019-09-26 12:15:59.911675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e154a69341'
down_revision = '6bdbd9ff70e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('request_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'request_uuid')
    # ### end Alembic commands ###
