"""Rename catalogue/catalog entity/collection

Revision ID: 2fd9f6e63f4c
Revises: 55dd54a938c9
Create Date: 2021-02-16 11:17:50.347307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd9f6e63f4c'
down_revision = '55dd54a938c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'catalogue', new_column_name='catalog')
    op.alter_column('logs', 'catalogue', new_column_name='catalog')
    op.alter_column('logs', 'entity', new_column_name='collection')
    op.create_index(op.f('ix_logs_catalog'), 'logs', ['catalog'], unique=False)
    op.create_index(op.f('ix_logs_collection'), 'logs', ['collection'], unique=False)
    op.drop_index('ix_logs_catalogue', table_name='logs')
    op.drop_index('ix_logs_entity', table_name='logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'catalog', new_column_name='catalogue')
    op.alter_column('logs', 'catalog', new_column_name='catalogue')
    op.alter_column('logs', 'collection', new_column_name='entity')
    op.create_index(op.f('ix_logs_catalogue'), 'logs', ['catalogue'], unique=False)
    op.create_index(op.f('ix_logs_entity'), 'logs', ['entity'], unique=False)
    op.drop_index('ix_logs_catalog', table_name='logs')
    op.drop_index('ix_logs_collection', table_name='logs')
    # ### end Alembic commands ###
