"""Add log_counts column to jobs table

Revision ID: 55dd54a938c9
Revises: 68ab67aaa7a6
Create Date: 2020-08-20 14:15:36.045172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55dd54a938c9'
down_revision = '68ab67aaa7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('log_counts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'log_counts')
    # ### end Alembic commands ###
