"""workflow

Revision ID: 56e1101414c1
Revises: ca22c23ad745
Create Date: 2019-02-06 15:18:32.243772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e1101414c1'
down_revision = 'ca22c23ad745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('args', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_end'), 'jobs', ['end'], unique=False)
    op.create_index(op.f('ix_jobs_start'), 'jobs', ['start'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('jobsteps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['jobid'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobsteps_end'), 'jobsteps', ['end'], unique=False)
    op.create_index(op.f('ix_jobsteps_start'), 'jobsteps', ['start'], unique=False)
    op.create_index(op.f('ix_jobsteps_status'), 'jobsteps', ['status'], unique=False)
    op.add_column('logs', sa.Column('jobid', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('stepid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logs', 'jobs', ['jobid'], ['id'])
    op.create_foreign_key(None, 'logs', 'jobsteps', ['stepid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_column('logs', 'stepid')
    op.drop_column('logs', 'jobid')
    op.drop_index(op.f('ix_jobsteps_status'), table_name='jobsteps')
    op.drop_index(op.f('ix_jobsteps_start'), table_name='jobsteps')
    op.drop_index(op.f('ix_jobsteps_end'), table_name='jobsteps')
    op.drop_table('jobsteps')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_start'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_end'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
