"""add services.timestamp index

Revision ID: 74bcff6671eb
Revises: efe251992c8c
Create Date: 2019-05-14 11:56:02.889336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74bcff6671eb'
down_revision = 'efe251992c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_timestamp_desc', 'services', [sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timestamp_desc', table_name='services')
    # ### end Alembic commands ###
