"""remove dst_queue

Revision ID: 7adb3a09dcbb
Revises: 0dec5fd9bb53
Create Date: 2019-06-27 16:05:02.537035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adb3a09dcbb'
down_revision = '0dec5fd9bb53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'dst_queue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('dst_queue', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
