"""delete bag onderzoeken jobs

Revision ID: 7e5fc5c3bc99
Revises: 9c0cb17f8956
Create Date: 2020-05-07 09:47:52.191262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5fc5c3bc99'
down_revision = '9c0cb17f8956'
branch_labels = None
depends_on = None


def upgrade():
    create_delete_job = """
create or replace function delete_job(_jobid integer) returns void
    language plpgsql
as $$
BEGIN
    delete from tasks where jobid=_jobid;
    delete from logs where jobid=_jobid;
    delete from jobsteps where jobid=_jobid;
    delete from jobs where id=_jobid;
END;
$$;
"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)

    op.execute(create_delete_job)
    # Delete BAG onderzoek jobs (replaced by BAG onderzoeken)
    op.execute("select delete_job(id) from jobs where 'bag'=ANY(args) AND 'onderzoek'=ANY(args)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    # ### end Alembic commands ###
