"""logid_desc

Revision ID: 9e8a5804884f
Revises: 74bcff6671eb
Create Date: 2019-05-15 09:46:44.270990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8a5804884f'
down_revision = '74bcff6671eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_logs_logid_desc', 'logs', [sa.text('logid DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_logid_desc', table_name='logs')
    # ### end Alembic commands ###
