"""Add catalogue, collection and attribute to Job entity

Revision ID: b9d5144c7fc9
Revises: 1b9a5052cc07
Create Date: 2020-08-06 15:13:02.046072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d5144c7fc9'
down_revision = '1b9a5052cc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('catalogue', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('collection', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('attribute', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'attribute')
    op.drop_column('jobs', 'collection')
    op.drop_column('jobs', 'catalogue')
    # ### end Alembic commands ###
