"""add extra header to task

Revision ID: c1d70cbb93f4
Revises: 7adb3a09dcbb
Create Date: 2019-07-03 14:33:27.782928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d70cbb93f4'
down_revision = '7adb3a09dcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('extra_header', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'extra_header')
    # ### end Alembic commands ###
