"""servicetasks

Revision ID: ca22c23ad745
Revises: fae8aea8a569
Create Date: 2019-01-29 07:34:15.107597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca22c23ad745'
down_revision = 'fae8aea8a569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tasks', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service_tasks', 'services', ['service_id'], ['id'])
    op.add_column('services', sa.Column('host', sa.String(), nullable=True))
    op.add_column('services', sa.Column('pid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_column('services', 'pid')
    op.drop_column('services', 'host')
    op.drop_constraint(None, 'service_tasks', type_='foreignkey')
    op.drop_column('service_tasks', 'service_id')
    # ### end Alembic commands ###
