"""Add application to logs

Revision ID: dc877bf28772
Revises: 05db559fe76f
Create Date: 2018-12-12 11:51:22.976617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc877bf28772'
down_revision = '05db559fe76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('application', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'application')
    # ### end Alembic commands ###
