"""jobs_overview

Revision ID: efe251992c8c
Revises: 56e1101414c1
Create Date: 2019-04-30 09:21:11.085910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe251992c8c'
down_revision = '56e1101414c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobsteps_id'), 'jobsteps', ['id'], unique=False)
    op.create_index(op.f('ix_jobsteps_jobid'), 'jobsteps', ['jobid'], unique=False)
    op.create_index(op.f('ix_logs_jobid'), 'logs', ['jobid'], unique=False)
    op.create_index(op.f('ix_logs_logid'), 'logs', ['logid'], unique=False)
    op.create_index(op.f('ix_logs_stepid'), 'logs', ['stepid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_stepid'), table_name='logs')
    op.drop_index(op.f('ix_logs_logid'), table_name='logs')
    op.drop_index(op.f('ix_logs_jobid'), table_name='logs')
    op.drop_index(op.f('ix_jobsteps_jobid'), table_name='jobsteps')
    op.drop_index(op.f('ix_jobsteps_id'), table_name='jobsteps')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    # ### end Alembic commands ###
