"""jobindex

Revision ID: fae8aea8a569
Revises: dc877bf28772
Create Date: 2019-01-23 15:44:30.424011

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fae8aea8a569'
down_revision = 'dc877bf28772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_logs_application'), 'logs', ['application'], unique=False)
    op.create_index(op.f('ix_logs_catalogue'), 'logs', ['catalogue'], unique=False)
    op.create_index(op.f('ix_logs_destination'), 'logs', ['destination'], unique=False)
    op.create_index(op.f('ix_logs_entity'), 'logs', ['entity'], unique=False)
    op.create_index(op.f('ix_logs_process_id'), 'logs', ['process_id'], unique=False)
    op.create_index(op.f('ix_logs_source'), 'logs', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_source'), table_name='logs')
    op.drop_index(op.f('ix_logs_process_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_entity'), table_name='logs')
    op.drop_index(op.f('ix_logs_destination'), table_name='logs')
    op.drop_index(op.f('ix_logs_catalogue'), table_name='logs')
    op.drop_index(op.f('ix_logs_application'), table_name='logs')
    # ### end Alembic commands ###
