FROM amsterdam/python:3.7-buster
MAINTAINER datapunt@amsterdam.nl

# Copy .jenkins scripts to where jenkins / ansible expect them
COPY .jenkins /.jenkins

# Install gobworkflow in /app folder
WORKDIR /app

# Install required Python packages
COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

# Copy gobworkflow module
COPY gobworkflow gobworkflow

# Copy test module
COPY tests tests

# Copy tests
COPY test.sh .flake8 ./