FROM amsterdam/docker_python:latest
MAINTAINER datapunt@amsterdam.nl

# Install gobworkflow in /app folder
WORKDIR /app

# Install required Python packages
COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

# Copy gobworkflow module
COPY gobworkflow gobworkflow

# Copy test module
COPY tests tests

# Copy tests
COPY test.sh .flake8 ./

# Copy jenkins files
COPY .jenkins /.jenkins
